name = "Fruitlands"
author = "Zed is not Dead"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa9825ef2798e49b4bdc9134324f5b85dfa6b48a603eba5945eeae999c8f8442"

[versions]
fabric = "0.14.23"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
