name = "Fruitlands"
author = "Zed is not Dead"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5005b4cd87be629d8c4db0fa8c594e72f63bccae8f6f2a04a38e794002758c90"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
