name = "Fruitlands"
author = "Zed is not Dead"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c5ca494db3333292f8a9d9a7e7f6e5929c48556d9ddc9cc1a3b4d10f22a5dd8"

[versions]
fabric = "0.14.23"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
