name = "Fruitlands"
author = "Zed is not Dead"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "585bb8e0b43ce4770dc44f3736ca7b8c455b21b475b05670dd7dad2a624a177c"

[versions]
fabric = "0.14.23"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.2"]
