# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				pig = true
				sheep = true
				chicken = true
				chest_minecart = true
				cow = true
				squid = true
				zombie = true
				glow_squid = true
				creeper = true
				zombie_villager = true
				skeleton = true
				bat = true
				drowned = true
				spider = true
				enderman = true
				witch = true
				item = true
				salmon = true
				cod = true
				villager = true
				tnt_minecart = true
				tropical_fish = true
				pufferfish = true
				rabbit = true
				polar_bear = true
				stray = true
				slime = true
				armor_stand = true
				wolf = true
				donkey = true
				dolphin = true
				turtle = true
				cave_spider = true
				fox = true
				bee = true
				horse = true
				boat = true
				axolotl = true
				husk = true
				trident = true
				allay = true
				arrow = true
				experience_orb = true
				ocelot = true

			[light_sources.settings.entities.graveyard]
				skeleton_creeper = true
				revenant = true
				nightmare = true
				acolyte = true
				ghoul = true
				corrupted_vindicator = true
				corrupted_pillager = true

			[light_sources.settings.entities.crittersandcompanions]
				koi_fish = true
				shima_enaga = true
				sea_bunny = true
				dumbo_octopus = true
				dragonfly = true
				otter = true
				leaf_insect = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.charm]
				coral_squid = true

